### PR TITLE
Reworked RogueSecondaryAttack.cs to make dash attack more encapsulated into a function

### PR DESCRIPTION
**Pull request by JakeHresh**
The main change made was to convert the dash attack into a more or less encapsulated function that is called after each right click. It is not entirely encapsulated since it relies on being executed over multiple frames. I attempted implementing a coroutine, but this produced undesirable effects. As a result, the partially encapsulated function is what I now offer. However, it should hopefully be simple enough to work around and for others implement code for dash attack animations. I also implemented cooldown for the dash attack.

### CODE REVIEW

**Review by donutcatscience — APPROVED** [review]
Thank you for all of your hard work Jacob! Can't wait to test this and see how it feels.

**Comment by deviantdear** [comment]
I noticed a few things that were broken in the branch and merged some changes to fix them before we merge this branch into develop. but otherwise I like the way the dash looks and feels. good job!

**Review by deviantdear — APPROVED** [review]
Ok to merge

**Review by Scanthrax — APPROVED** [review]
Should be good to merge; going to double-check with Val really quick

**Pull request merged**
